imports:
- { resource: parameters.yml }

parameters:
  locale: en

framework:
  secret: '%secret%'
  validation: { enable_annotations: true }
  default_locale: '%locale%'
  trusted_hosts: ~
  fragments: ~
  http_method_override: true
  php_errors:
    log: true

doctrine:
  dbal:
    driver: '%database_type%'
    host: '%database_host%'
    port: '%database_port%'
    dbname: '%database_name%'
    user: '%database_user%'
    password: '%database_password%'
    charset: UTF8

dv_evil_queue:
  debug: "%kernel.debug%"
  connection: "@doctrine.dbal.default_connection"
  logger: "@logger"
  workers: '%workers_regular%'
  priority_workers: '%workers_priority%'
